#ifndef CONSTANTES_H
#define CONSTANTES_H

#define MAX_STRING 1000
#define MAX_ARREGLO 200
#define MAX_ERRORES 200
#define CANTIDAD_REGISTROS 32
#define CANTIDAD_FUNCIONES 10
#define CAPACIDAD_MEMORIA 64

#endif /*CONSTANTES_H*/